"""Add multi-platform fields

Revision ID: f52ab1b28049
Revises: 
Create Date: 2025-11-26 14:11:13.689327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52ab1b28049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('duration')
        batch_op.drop_column('platform')
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
